### ISSUE TITLE
Remove un-needed branches.

### ISSUE THREAD

**Issue by AVCADO** [novavita/Novix#20]
This'll help with having a clean codebase.

Here are the links for merged/useless branches as of  10/4/20:

[Paging](https://github.com/novavita/Novix/tree/work/paging) - Author: Jan Pontaoski
[Restructure](https://github.com/novavita/Novix/tree/work/pontaoski/restructure) - Author: Jan Pontaoski
[Restructure CI](https://github.com/novavita/Novix/tree/work/hellcp/restructure-ci) - Author: HellCP
[Repo Info](https://github.com/novavita/Novix/tree/work/pontaoski/repoinfo) - Author: Jan Pontaoski

**Comment by faintwary** [comment]
So do it yourself tf
